name: Publish package

on:
  workflow_dispatch:
    inputs:
      versionBumpType:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.publish.outputs.latest-version }}
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - name: Check permission
        if: ${{ !contains('["17008875","33892812"]', github.actor_id) }}
        run: echo 'Permission denied' && exit 1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Compile
        run: yarn run build
      - name: Bump & publish package
        run: yarn version --${{ inputs.versionBumpType }} --no-git-tag-version && npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: publish
        name: Output variables
        run: echo "latest-version=$(npm view bucket-protocol-sdk version)" >> "$GITHUB_OUTPUT"
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: bump sdk version'
  create-pr:
    runs-on: ubuntu-latest
    needs: publish
    strategy:
      matrix:
        repo:
          - bucket-frontend-v4
          - bucket-frontend-v5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Bucket-Protocol/${{ matrix.repo }}
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Bump version
        run: |
          yarn upgrade bucket-protocol-sdk@${{ needs.publish.outputs.latest-version }}  --save-exact
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: bump-bucket-protocol-sdk-v${{ needs.publish.outputs.latest-version }}
          title: 'chore: bump bucket-protocol-sdk to v${{ needs.publish.outputs.latest-version }}'
          token: ${{ secrets.ADMIN_TOKEN }}
