name: Publish package

on:
  workflow_dispatch:
    inputs:
      version-bump-type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Check permission
      #   if: ${{ !contains('["17008875", "33892812", "2819672"]', github.actor_id) }}
      #   run: echo 'Permission denied' && exit 1
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile
        run: pnpm build
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump package version
        run: pnpm version ${{ inputs.version-bump-type }} --no-git-tag-version
      - name: Publish package to NPM
        run: pnpm publish --provenance --access public --no-git-checks --dry-run
      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore(release): bump sdk version to new release'

  create-pr:
    runs-on: ubuntu-latest
    needs: publish
    strategy:
      matrix:
        repo:
          - bucket-frontend-v5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: Bucket-Protocol/${{ matrix.repo }}
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Bump version
        id: bump-version
        run: |
          pnpm upgrade @bucket-protocol/sdk --latest --save-exact
          echo SDK_VERSION=$(pnpm info @bucket-protocol/sdk version) >> "$GITHUB_OUTPUT"
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: bump-bucket-protocol-sdk-${{ steps.bump-version.outputs.SDK_VERSION }}
          title: 'chore: bump bucket-protocol-sdk to ${{ steps.bump-version.outputs.SDK_VERSION }}'
          token: ${{ secrets.ADMIN_TOKEN }}
